use crate::glossary::WordEntry;
use genanki_rs::{Deck, Field, Model, Note, Template};
use std::error::Error;

pub fn generate_anki_deck(
    merged_entries: &[WordEntry],
    deck_name: &str,
    output_path: &str,
) -> Result<(), Box<dyn Error + Send + Sync>> {
    let model = Model::new(
        1607392319,
        "Glost Note Type",
        vec![
            Field::new("Word"),
            Field::new("Meaning"),
            Field::new("POS"),
            Field::new("Context"),
            Field::new("Language"),
            Field::new("Frequency"),
        ],
        vec![Template::new("Card 1")
            .qfmt("<div style='font-family: Arial; font-size: 30px; text-align: center; color: #2c3e50;'>{{Word}}</div>")
            .afmt(r#"
                <div style='font-family: Arial; font-size: 30px; text-align: center; color: #2c3e50; border-bottom: 1px solid #eee; padding-bottom: 10px;'>{{Word}}</div>
                <div style='font-family: Arial; font-size: 18px; color: #7f8c8d; margin-top: 10px; font-style: italic;'>{{POS}} ({{Language}})</div>
                <div style='font-family: Arial; font-size: 20px; color: #34495e; margin-top: 20px;'>{{Meaning}}</div>
                {{#Context}}
                <div style='font-family: Georgia, serif; font-size: 16px; color: #95a5a6; margin-top: 30px; padding: 15px; background: #f9f9f9; border-left: 5px solid #bdc3c7; font-style: italic;'>
                    "{{Context}}"
                </div>
                {{/Context}}
                <div style='font-family: Arial; font-size: 12px; color: #bdc3c7; margin-top: 20px; text-align: right;'>Frequency: {{Frequency}}</div>
            "#)],
    );

    let mut deck = Deck::new(1234567890, deck_name, "Generated by Glost");

    for entry in merged_entries {
        let meaning_html = if entry.meaning.contains(" | ") {
            let mut html = String::from("<ul style='text-align: left; display: inline-block;'>");
            for part in entry.meaning.split(" | ") {
                html.push_str(&format!("<li>{}</li>", part.replace("*", "")));
            }
            html.push_str("</ul>");
            html
        } else {
            entry.meaning.replace("*", "")
        };

        let note = Note::new(
            model.clone(),
            vec![
                &entry.word,
                &meaning_html,
                &entry.pos.to_string(),
                entry.context.as_deref().unwrap_or(""),
                &entry.lang.to_string(),
                &entry.frequency.to_string(),
            ],
        )?;
        deck.add_note(note);
    }

    deck.write_to_file(output_path)?;

    Ok(())
}
