use crate::glossary::WordEntry;
use genanki_rs::{Deck, Field, Model, Note, Template};
use std::error::Error;

pub fn generate_anki_deck(
    merged_entries: &[WordEntry],
    deck_name: &str,
    output_path: &str,
) -> Result<(), Box<dyn Error + Send + Sync>> {
    let model = Model::new(
        1607392319,
        "Glost Note Type v2",
        vec![
            Field::new("Word"),
            Field::new("Meaning"),
            Field::new("POS"),
            Field::new("Context"),
            Field::new("Language"),
            Field::new("Frequency"),
            Field::new("CEFR"),
            Field::new("Grammar"),
            Field::new("Audio"),
        ],
        vec![Template::new("Card 1")
            .qfmt(r#"
                <div style='font-family: Arial; font-size: 30px; text-align: center; color: #2c3e50;'>
                    {{Word}}
                    <div style='margin-top: 10px;'>{{Audio}}</div>
                </div>
            "#)
            .afmt(r#"
                <div style='font-family: Arial; font-size: 30px; text-align: center; color: #2c3e50; border-bottom: 1px solid #eee; padding-bottom: 10px;'>
                    {{Word}}
                    <div style='margin-top: 10px;'>{{Audio}}</div>
                </div>
                
                <div style='display: flex; justify-content: center; gap: 10px; margin-top: 10px;'>
                    <div style='font-family: Arial; font-size: 14px; color: white; background: #3498db; padding: 2px 8px; border-radius: 4px; font-weight: bold;'>{{Language}}</div>
                    <div style='font-family: Arial; font-size: 14px; color: #7f8c8d; font-style: italic;'>{{POS}}</div>
                    {{#CEFR}}
                    <div style='font-family: Arial; font-size: 14px; color: white; background: #e67e22; padding: 2px 8px; border-radius: 4px; font-weight: bold;'>{{CEFR}}</div>
                    {{/CEFR}}
                </div>

                <div style='font-family: Arial; font-size: 20px; color: #34495e; margin-top: 20px; text-align: center;'>{{Meaning}}</div>

                {{#Grammar}}
                <div style='font-family: Arial; font-size: 16px; color: #27ae60; margin-top: 20px; padding: 10px; border: 1px dashed #27ae60; border-radius: 5px; background: #fafffa;'>
                    <b>Grammar:</b> {{Grammar}}
                </div>
                {{/Grammar}}

                {{#Context}}
                <div style='font-family: Georgia, serif; font-size: 16px; color: #95a5a6; margin-top: 30px; padding: 15px; background: #f9f9f9; border-left: 5px solid #bdc3c7; font-style: italic;'>
                    "{{Context}}"
                </div>
                {{/Context}}

                <div style='font-family: Arial; font-size: 12px; color: #bdc3c7; margin-top: 20px; text-align: right;'>Frequency: {{Frequency}}</div>
            "#)],
    );

    let mut deck = Deck::new(1234567890, deck_name, "Generated by Glost");
    let mut media_files = Vec::new();

    for entry in merged_entries {
        let meaning_html = if entry.meaning.contains(" | ") {
            let mut html = String::from("<ul style='text-align: left; display: inline-block;'>");
            for part in entry.meaning.split(" | ") {
                html.push_str(&format!("<li>{}</li>", part.replace("*", "")));
            }
            html.push_str("</ul>");
            html
        } else {
            entry.meaning.replace("*", "")
        };

        let audio_field = if let Some(path) = &entry.audio_path {
            let filename = std::path::Path::new(path).file_name().unwrap().to_str().unwrap();
            media_files.push(path.as_str());
            format!("[sound:{}]", filename)
        } else {
            String::new()
        };

        let note = Note::new(
            model.clone(),
            vec![
                &entry.word,
                &meaning_html,
                &entry.pos.to_string(),
                entry.context.as_deref().unwrap_or(""),
                &entry.lang.to_string(),
                &entry.frequency.to_string(),
                entry.cefr_level.as_deref().unwrap_or(""),
                entry.grammar_note.as_deref().unwrap_or(""),
                &audio_field,
            ],
        )?;
        deck.add_note(note);
    }

    let mut package = genanki_rs::Package::new(vec![deck], media_files)?;
    package.write_to_file(output_path)?;

    Ok(())
}
